version: '3.7'

services:
  auth-db:
    image: postgres:14
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    ports:
      - 54320:5432
    env_file:
      - ./.env

  auth-redis:
    image: redis:6.0-alpine
    volumes:
      - redis_volume_auth:/data
    env_file:
      - ./.env
    ports:
      - 6379:6379
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'

volumes:
  auth_postgres_data:
  redis_volume_auth:
